### ISSUE TITLE
Show multiple category AI predicted labels feature for flow.depegis 

### ISSUE THREAD

**Issue by darknight-007** [DREAMS-lab/deepgis#34]
![image](https://user-images.githubusercontent.com/3958994/102022050-7892fe80-3d41-11eb-9d0a-5f91ee29c709.png)

**Comment by harishanand95** [comment]
Added the feature in flow deepgis

- [ ] TODO: fix the categorytype order for training and prediction to be consistent (hard coded currently in flow). Weirdly the order changes every time all the categorytype objects are retrieved.
- [x] Added multi category AI prediction. Class labels are sent to the label.html along with SVG from views.py

**Comment by harishanand95** [comment]
Feature added in commit https://github.com/DREAMS-lab/deepgis/commit/8e13c171effdd147e25f60a3dba2404b9eaf8f18

**Comment by darknight-007** [comment]
Thanks @harishanand95 !
